#goal   
geometry_msgs/Pose home
geometry_msgs/Pose target
geometry_msgs/Pose back
float64 sleep
float64 max_accel
float64 max_angaccel
float64 stop_time
float64 stop_factor
---
#result
int64 success
---
#feedback
int64 percentage